### ISSUE TITLE
Libclang on hackage doesn't compile (github master does compile)

### ISSUE THREAD

**Issue by anderspapitto** [chetant/LibClang#39]
Version 0.1.0 from hackage gives the error

src/Clang/FFI_stub_ffi.c:411:12:
     error: ‘CXTranslationUnit_CXXPrecompiledPreamble’ undeclared (first use in this function)
       do {res1=CXTranslationUnit_CXXPrecompiledPreamble;

whereas the master branch on github builds successfully. If I diff FFI_stub_ffi.c between the two, there are indeed differences - I would expect them to match..

I have ghc 7.6.3 and clang version 3.3

**Comment by abbradar** [comment]
Any updates? Even if the package is not quite ready yet, it's better than to have a non-working version on Hackage.

**Comment by alexanderkyte** [comment]
Still?

**Comment by chetant** [comment]
I've updated Hackage with the package as of 20c018292a2e404206d8974f2a40aa102141dbb2
Could someone with OS X verify that the package builds from hackage?

**Comment by chetant** [comment]
Marking this as closed. Please open a new ticket if anyone encounters OS X build issues.
