### ISSUE TITLE
Add an option to use out-of-tree llvm and clang

### ISSUE THREAD

**Issue by abbradar** [chetant/LibClang#50]
If I understood correcty, you use LLVM/CLang 3.4 without any significant patches. An option to use out-of-tree libraries would be great -- to reduce compilation times of clean tree and to re-use existing libraries from the system -- e.g. on Linux where they are provided already by package managers. I could have overlooked some reason because of which you build them in-tree -- I'm sorry if this is the case.

**Comment by chetant** [comment]
@abbradar master builds against out of tree LLVM 3.8
