### ISSUE TITLE
De-couple from Greencard

### ISSUE THREAD

**Issue by deech** [chetant/LibClang#54]
Hi,
I would like to use Libclang it depends on Greencard which does not build on the latest GHC (7.10.x). I have made attempts to contact the maintainer but haven't heard back. Furthermore it seems like a dead project anyway. To that end I am working on converting `FFI.gc` to `FFI.chs` so that `c2hs` , which is being actively developed, is used instead of `Greencard`. Are you willing to merge in such a change when I'm done?

**Comment by chetant** [comment]
If greencard isn't working on ghc 7.10, then yes please! Greencard has seen
slow updates and my attempts to contact the maintainer didn't go anywhere
either. Moving to c2hs would probably be a good idea.

**Comment by ghorn** [comment]
Greencard has been a continuous source of trouble. See #9, #36, #45.

**Comment by chetant** [comment]
closed as of 502d498b759776ba9341c96a854a0217872021ab
