### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by deech** [chetant/LibClang#65]
Hi,
I guess this release doesn't build LLVM statically like it used to. A big advantage was that resulting binaries weren't dependent on the user having installed LLVM. Would a PR that used a flag to trigger the old functionality (static build, not bundled libraries) be welcome?

**Comment by chetant** [comment]
Yes, always!

**Comment by abarbu** [comment]
@deech Yes please! If you have this change can you post a PR? Taking away static linking made this library unusable :(

**Comment by chetant** [comment]
Merged #66, sorry for the delay.
